#!/usr/local/bin/zsh

chsh -s $(which zsh)

# create default shell for user
dscl . -create /Users/$USER UserShell $(which zsh)

source ~/.zshrc

# fonts
cp -r $DOTFILES/fonts/. ~/Library/Fonts

ITERM_PROFILES = "$HOME/Library/Application Support/iTerm2/DynamicProfiles"

if [ ! -d "$ITERM_PROFILES" ]; then
  mkdir -p "$ITERM_PROFILES"
fi

cp $DOTFILES/fonts/profiles.json $ITERM_PROFILES

code --install-extension "Shan.code-settings-sync"

# Fix for pyenv on Mjave 10.14+
# https://github.com/pyenv/pyenv/wiki/Common-build-problems
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

# o-my-zsh
env git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git "~/.oh-my-zsh" || {
    printf "Error: git clone of oh-my-zsh repo failed\n"
    exit 1
  }
